class_languages = {
    "Fotografía Nocturna: Captura Imágenes Nocturnas como Nadie": 'es',
    "Masterclass de Google SEO: Posiciónate Alto con un Mejor SEO": 'es',
    "Marketing de Contenidos para Principiantes: La Guía Completa": 'es',
    "YouTube Masterclass - La Guía Completa de Youtube": 'es',
    "Curso Completo de Marketing Digital - 23 Cursos en 1": 'es',
    "Adobe Lightroom CC+Classic: Masterclass de Edición de Fotos": 'es',
    "Adobe Premiere Pro CC para Principiantes: Edición de Videos": 'es',
    "After Effects CC Masterclass - Actualizado a CC 2020": 'es',
    "Photoshop CC para Principiantes - Actualizado a CC 2019": 'es',
    "Fotografía de Comida: Capturando la Comida en Tu Cocina": 'es',
    "Fotografía Masterclass: Una Guía Completa para la Fotografía": 'es',
    "Producción de Videos: el Entrenamiento Absoluto": 'es',
    "佳能Canon数码相机完全使用指南": 'zh-cn',
    "YouTube大师课之如何成为YouTube红人": 'zh-cn',
    "专业影视拍摄：用任何摄像机都能拍出更好的视频！": 'zh-cn',
    "摄影大师课：最佳在线专业摄影课": 'zh-cn',
    "街头摄影完全指南": 'zh-cn',
    "用摄像头制作专业水准录播课": 'zh-cn',
    "摄影基础快速入门": 'zh-cn',
    "风景摄影完全指南": 'zh-cn',
    "Ae实战之《纸牌屋》入场动画": 'zh-cn',
    "美食摄影：展示我家厨房里的美食": 'zh-cn',
    "Adobe Lightroom CC + Classic CC：照片后期大师课": 'zh-cn',
    "婚礼摄影完全教程": 'zh-cn',
    "零基础视频拍摄完全教程": 'zh-cn',
    "零基础入门After Effects CC": 'zh-cn',
    "零基础入门Premiere Pro CC": 'zh-cn',
    "夜景拍摄实战完全指南": 'zh-cn',
    "After Effects实战：制作时髦勋章前贴动效": 'zh-cn',
    "After Effects实战：字体动效速成课": 'zh-cn',
    "成为小小摄影师": 'zh-cn',
    "DIY Food Photography : Fotografalo nella Tua Cucina!": 'it',
    "Fotografia Masterclass: La Tua Guida Completa Alla Fotografia": 'it',
    "Photographie Masterclass: Guide Complet de la Photographie": 'fr',
    "Adobe After Effects CC 2020 : دليلك الكامل من الصفر للإحتراف": 'ar',
    "Adobe Premiere Pro CC: Łatwy Montaż Wideo w Premiere Pro": 'pl',
    "Fotografia Masterclass: Um Guia Completo de Fotografia": 'pt'
}

languages = ['es', 'zh-cn', 'it', 'fr', 'ar', 'pl', 'pt', 'en']